# Stage 1: Building the app
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock) to workdir
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of your app's source code
COPY . .

# Build your Next.js app
RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]
